enum TestReportCause {
    SEXUAL_HARASSMENT,
    HARASSMENT,
    RACISM,
    INCORRECT_QUESTIONS,
    MISLEADING_ANSWERS,
    MANIPULATION,
    TOO_MUCH_POINTS,
    TOO_LITTLE_POINTS
}

export {TestReportCause};